f = open('demo.txt','w')
f.write("Hello From Bharath")
f.close()
# f = open('demo.txt','r')
# print(f.read())

f = open('demo.txt','a')
f.write('\nNice to meet you')
f.close()

f= open('demo.txt','+a')
f.write("\nappending the line")
f.close()

f = open('demo.txt','r')
print(f.read())
print(f.tell())
f.seek(10)
print(f.tell())
f = open('demo.txt','a')
f.write("apeending")
f = open('demo.txt','r')
print(f.read())
f.close()
